version: "3.3"
services:
    common:
        build: spread_game/.
        command: "npm install"
    web:
        build: server/.
        ports:
            - "4001:4001"
        environment:
            - PORT=4001
        command: "npm run start"
        depends_on:
            - common
    ui:
        build: client/.
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
        command: "npm run start"
        depends_on:
            - common
        stdin_open: true
