version: "3.3"
services:
    common:
        build: spread_game/.
        command: "npm run test"
    web:
        build: server/.
        ports:
            - "4001:4001"
        environment:
            - PORT=4001
            - BASE_URL=localhost
        command: "npm run test"
        depends_on:
            - common
    ui:
        build: client/.
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
            - REACT_APP_WEB_API_PORT=4001
            - REACT_APP_WEB_API_BASE_URL=localhost
        command: "npm run test"
        depends_on:
            - common
        stdin_open: true
    integration_tests:
        build: integration_tests/.
        command: "npm run test"
        depends_on:
            - ui
            - web
