version: "3.3"
services:
    web:
        build: server/.
        ports:
            - "8010:8010"
        environment:
            - port=8010
        command: "npm run start"
    ui:
        build: client/.
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
        command: "npm run start"
        stdin_open: true