name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build common
      run: docker build -t spread_common --file spread_game/Dockerfile spread_game/.
      
    - name: Build client
      run: docker build -t spread_client --file client/Dockerfile client/.
        
    - name: Build and push client production
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./client/Dockerfile.Production
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spread_client:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
